version: "3.7"
services:
  portainer:
    image: portainer/portainer-ce:2.9.3
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
  nginx:
    image: nginx:1.22.0-alpine
    hostname: nginx
    container_name: nginx
    restart: unless-stopped
    environment:
      - NGINX_HOST=mineralos.net
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - 80:80
  mariadb:
    image: mariadb:10.9.3
    container_name: mariadb
    restart: unless-stopped
    environment:
      # ROOT Password Only For Initialization Setup (Please Change After Running)
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
  filerun:
    image: filerun/filerun
    environment:
      FR_DB_HOST: mariadb
      FR_DB_PORT: 3306
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb
    ports:
      - "8888:80"
    volumes:
      - filerun-html:/var/www/html
      - filerun-user-files:/user-files
volumes:
  portainer-data:
  mariadb-data:
  filerun-user-files:
  filerun-html:
