version: "3.7"

services:
  portainer:
    image: portainer/portainer-ce:2.15.1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    ports:
      - '9443:9443'

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${MARIADB_USER}
      DB_MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      DB_MYSQL_NAME: ${NGINX_PROXY_MANAGER_DB}
    volumes:
      - nginx-proxy-manager-data:/data
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  
  db:
    image: mariadb:10.9.3
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${NGINX_PROXY_MANAGER_DB}
    volumes:
      - nginx-proxy-manager-db:/var/lib/mysql

volumes:
  nginx-proxy-manager-data:
  nginx-proxy-manager-db:
  portainer-data:
